services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on: 
      db:
        condition: service_healthy
    volumes:
      - .:/app/
      - model_cache:/root/.cache/huggingface

  db:
    image: ankane/pgvector
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  model_cache:


